# Based on http://conda.pydata.org/docs/travis.html
language: python
sudo: false # use container based build
notifications:
  email: false

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: CONDA_ENV=py27
  - python: 2.7
    env: CONDA_ENV=py27_netcdf4331

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update -q conda
  - conda info -a
  #- git clone https://github.com/laliberte/netcdf4_soft_links.git
  #- git clone https://github.com/laliberte/netcdf4_pydap.git

install:
  - conda env create --file ci/requirements-$CONDA_ENV.yml
  - source activate test_env
  - python setup.py install
  #- cd netcdf4_soft_links
  #- python setup.py install
  #- cd ..
  #- cd netcdf4_pydap
  #- python setup.py install
  #- cd ..

script:
  - bash cdb_query/recipes/recipe01.sh 
  - bash cdb_query/recipes/recipe03.sh 
  - bash cdb_query/recipes/recipe04.sh 
  - bash cdb_query/recipes/recipe05.sh 
  - bash cdb_query/recipes/recipe06.sh 
  - bash cdb_query/recipes/recipe08.sh compute 10
