# Based on http://conda.pydata.org/docs/travis.html
language: python
sudo: false # use container based build
notifications:
  email: false

os:
  - linux
  - osx

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: CONDA_ENV=py27
    - python: 2.7
      env: CONDA_ENV=py27_netcdf4331
  allow_failures:
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O minconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update -q conda
  - conda info -a
  #- git clone https://github.com/laliberte/netcdf4_pydap.git
  #- git clone https://github.com/laliberte/netcdf4_soft_links.git

install:
  - conda env create --file ci/requirements-$CONDA_ENV.yml
  - source activate test_env
  #- cd netcdf4_pydap
  #- python setup.py install
  #- cd ..
  #- cd netcdf4_soft_links
  #- python setup.py install
  #- cd ..
  - python setup.py install

script:
  - bash cdb_query/recipes/recipe01.sh 
  - bash cdb_query/recipes/recipe03.sh 
  - bash cdb_query/recipes/recipe04.sh 
  # Skip cdo-based recipe. conda cdo with netcdf 4.3.3.1 appears broken
  - if [[ $CONDA_ENV != 'py27_netcdf4331' ]]; then bash cdb_query/recipes/recipe05.sh; fi
  - bash cdb_query/recipes/recipe06.sh 
  - bash cdb_query/recipes/recipe08.sh compute 10
