# Based on http://conda.pydata.org/docs/travis.html
language: python
sudo: false # use container based build
notifications:
  email: false

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 2.7
      env: CONDA_ENV=py27

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update -q conda
  - conda info -a

install:
  - conda env create --file ci/requirements-$CONDA_ENV.yml
  - source activate cdb_query_test_env
  - pip install -e .[testing]

script:
  # The first recipe is a bit longer. Prevent TRAVIS from exiting early:
  - flake8
  - travis_wait 25 bash cdb_query/recipes/recipe01.sh test 
  - bash cdb_query/recipes/recipe03.sh test
  - bash cdb_query/recipes/recipe04.sh test
  - bash cdb_query/recipes/recipe05.sh test
  - bash cdb_query/recipes/recipe06.sh test
  - bash cdb_query/recipes/recipe07.sh test
  - bash cdb_query/recipes/recipe08.sh test
